/*----- PROTECTED REGION ID(MAGSrvClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        MAGSrvClass.cpp
//
// description : C++ source for the MAGSrvClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the MAGSrv once per process.
//
// project :
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MAGSrvClass.h>

/*----- PROTECTED REGION END -----*/	//	MAGSrvClass.cpp

//-------------------------------------------------------------------
/**
 *	Create MAGSrvClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_MAGSrv_class(const char *name) {
		return MAGSrv_ns::MAGSrvClass::init(name);
	}
}

namespace MAGSrv_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
MAGSrvClass *MAGSrvClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		MAGSrvClass::MAGSrvClass(string &s)
 * description : 	constructor for the MAGSrvClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
MAGSrvClass::MAGSrvClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering MAGSrvClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(MAGSrvClass::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::constructor

	cout2 << "Leaving MAGSrvClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		MAGSrvClass::~MAGSrvClass()
 * description : 	destructor for the MAGSrvClass
 */
//--------------------------------------------------------
MAGSrvClass::~MAGSrvClass()
{
	/*----- PROTECTED REGION ID(MAGSrvClass::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		MAGSrvClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
MAGSrvClass *MAGSrvClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new MAGSrvClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		MAGSrvClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
MAGSrvClass *MAGSrvClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StartClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartClass::execute(): arrived" << endl;
	((static_cast<MAGSrv *>(device))->start());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<MAGSrv *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;
	((static_cast<MAGSrv *>(device))->reset());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		getErrorClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *getErrorClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "getErrorClass::execute(): arrived" << endl;
	Tango::DevUShort argin;
	extract(in_any, argin);
	return insert((static_cast<MAGSrv *>(device))->get_error(argin));
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum MAGSrvClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum MAGSrvClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum MAGSrvClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void MAGSrvClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "proxy";
	prop_desc = "Communication proxy with the serial device";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "address";
	prop_desc = "RS485 address of the pump (from 0 to 31)";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "polling";
	prop_desc = "Pump status polling time";
	prop_def  = "500";
	vect_data.clear();
	vect_data.push_back("500");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void MAGSrvClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Device server for MagDrive frequency converters mounted on Leybold Turbopumps.");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void MAGSrvClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(MAGSrvClass::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new MAGSrv(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		MAGSrv *dev = static_cast<MAGSrv *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(MAGSrvClass::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void MAGSrvClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(MAGSrvClass::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::attribute_factory_before
	//	Attribute : Frequency
	FrequencyAttrib	*frequency = new FrequencyAttrib();
	Tango::UserDefaultAttrProp	frequency_prop;
	frequency_prop.set_description("Actual output frequency of the converter");
	frequency_prop.set_label("Frequency");
	frequency_prop.set_unit("Hz");
	frequency_prop.set_standard_unit("Hz");
	frequency_prop.set_display_unit("Hz");
	frequency_prop.set_format("%d");
	//	max_value	not set for Frequency
	//	min_value	not set for Frequency
	//	max_alarm	not set for Frequency
	//	min_alarm	not set for Frequency
	//	max_warning	not set for Frequency
	//	min_warning	not set for Frequency
	//	delta_t	not set for Frequency
	//	delta_val	not set for Frequency
	
	frequency->set_default_properties(frequency_prop);
	//	Not Polled
	frequency->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	frequency->set_change_event(true, false);
	att_list.push_back(frequency);

	//	Attribute : MotorTemperature
	MotorTemperatureAttrib	*motortemperature = new MotorTemperatureAttrib();
	Tango::UserDefaultAttrProp	motortemperature_prop;
	motortemperature_prop.set_description("Actual motor temperature");
	motortemperature_prop.set_label("Motor temperature");
	motortemperature_prop.set_unit("°C");
	motortemperature_prop.set_standard_unit("°C");
	motortemperature_prop.set_display_unit("°C");
	motortemperature_prop.set_format("%d");
	//	max_value	not set for MotorTemperature
	//	min_value	not set for MotorTemperature
	//	max_alarm	not set for MotorTemperature
	//	min_alarm	not set for MotorTemperature
	//	max_warning	not set for MotorTemperature
	//	min_warning	not set for MotorTemperature
	//	delta_t	not set for MotorTemperature
	//	delta_val	not set for MotorTemperature
	
	motortemperature->set_default_properties(motortemperature_prop);
	//	Not Polled
	motortemperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	motortemperature->set_change_event(true, false);
	att_list.push_back(motortemperature);

	//	Attribute : ConverterTemperature
	ConverterTemperatureAttrib	*convertertemperature = new ConverterTemperatureAttrib();
	Tango::UserDefaultAttrProp	convertertemperature_prop;
	convertertemperature_prop.set_description("Actual converter temperature");
	convertertemperature_prop.set_label("Converter temperature");
	convertertemperature_prop.set_unit("°C");
	convertertemperature_prop.set_standard_unit("°C");
	convertertemperature_prop.set_display_unit("°C");
	convertertemperature_prop.set_format("%d");
	//	max_value	not set for ConverterTemperature
	//	min_value	not set for ConverterTemperature
	//	max_alarm	not set for ConverterTemperature
	//	min_alarm	not set for ConverterTemperature
	//	max_warning	not set for ConverterTemperature
	//	min_warning	not set for ConverterTemperature
	//	delta_t	not set for ConverterTemperature
	//	delta_val	not set for ConverterTemperature
	
	convertertemperature->set_default_properties(convertertemperature_prop);
	//	Not Polled
	convertertemperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	convertertemperature->set_change_event(true, false);
	att_list.push_back(convertertemperature);

	//	Attribute : OperatingHours
	OperatingHoursAttrib	*operatinghours = new OperatingHoursAttrib();
	Tango::UserDefaultAttrProp	operatinghours_prop;
	//	description	not set for OperatingHours
	operatinghours_prop.set_label("Total operating hours");
	operatinghours_prop.set_unit("h");
	operatinghours_prop.set_standard_unit("h");
	operatinghours_prop.set_display_unit("h");
	operatinghours_prop.set_format("%.2f");
	//	max_value	not set for OperatingHours
	//	min_value	not set for OperatingHours
	//	max_alarm	not set for OperatingHours
	//	min_alarm	not set for OperatingHours
	//	max_warning	not set for OperatingHours
	//	min_warning	not set for OperatingHours
	//	delta_t	not set for OperatingHours
	//	delta_val	not set for OperatingHours
	
	operatinghours->set_default_properties(operatinghours_prop);
	//	Not Polled
	operatinghours->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	operatinghours->set_change_event(true, false);
	att_list.push_back(operatinghours);

	//	Attribute : Current
	CurrentAttrib	*current = new CurrentAttrib();
	Tango::UserDefaultAttrProp	current_prop;
	current_prop.set_description("Actual current value of the intermediate circuit of the frequency converter");
	current_prop.set_label("Current");
	current_prop.set_unit("A");
	current_prop.set_standard_unit("A");
	current_prop.set_display_unit("A");
	current_prop.set_format("%.1f");
	//	max_value	not set for Current
	//	min_value	not set for Current
	//	max_alarm	not set for Current
	//	min_alarm	not set for Current
	//	max_warning	not set for Current
	//	min_warning	not set for Current
	//	delta_t	not set for Current
	//	delta_val	not set for Current
	
	current->set_default_properties(current_prop);
	//	Not Polled
	current->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	current->set_change_event(true, false);
	att_list.push_back(current);

	//	Attribute : BearingTemperature
	BearingTemperatureAttrib	*bearingtemperature = new BearingTemperatureAttrib();
	Tango::UserDefaultAttrProp	bearingtemperature_prop;
	bearingtemperature_prop.set_description("Actual bearing temperature");
	bearingtemperature_prop.set_label("Bearing temperature");
	bearingtemperature_prop.set_unit("°C");
	bearingtemperature_prop.set_standard_unit("°C");
	bearingtemperature_prop.set_display_unit("°C");
	bearingtemperature_prop.set_format("%d");
	//	max_value	not set for BearingTemperature
	//	min_value	not set for BearingTemperature
	//	max_alarm	not set for BearingTemperature
	//	min_alarm	not set for BearingTemperature
	//	max_warning	not set for BearingTemperature
	//	min_warning	not set for BearingTemperature
	//	delta_t	not set for BearingTemperature
	//	delta_val	not set for BearingTemperature
	
	bearingtemperature->set_default_properties(bearingtemperature_prop);
	//	Not Polled
	bearingtemperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	bearingtemperature->set_change_event(true, false);
	att_list.push_back(bearingtemperature);

	//	Attribute : Power
	PowerAttrib	*power = new PowerAttrib();
	Tango::UserDefaultAttrProp	power_prop;
	power_prop.set_description("Power consumption");
	power_prop.set_label("Power");
	power_prop.set_unit("W");
	power_prop.set_standard_unit("W");
	power_prop.set_display_unit("W");
	power_prop.set_format("%.1f");
	//	max_value	not set for Power
	//	min_value	not set for Power
	//	max_alarm	not set for Power
	//	min_alarm	not set for Power
	//	max_warning	not set for Power
	//	min_warning	not set for Power
	//	delta_t	not set for Power
	//	delta_val	not set for Power
	
	power->set_default_properties(power_prop);
	//	Not Polled
	power->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	power->set_change_event(true, false);
	att_list.push_back(power);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(MAGSrvClass::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void MAGSrvClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(MAGSrvClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::pipe_factory_before
	/*----- PROTECTED REGION ID(MAGSrvClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void MAGSrvClass::command_factory()
{
	/*----- PROTECTED REGION ID(MAGSrvClass::command_factory_before) ENABLED START -----*/

	// Set 500 ms polling perod for command State
	Tango::Command &stateCmd = get_cmd_by_name("State");
	stateCmd.set_polling_period(500);

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::command_factory_before


	//	Command Start
	StartClass	*pStartCmd =
		new StartClass("Start",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCmd);

	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	//	Command Reset
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);

	//	Command getError
	getErrorClass	*pgetErrorCmd =
		new getErrorClass("getError",
			Tango::DEV_USHORT, Tango::DEV_STRING,
			"Error index (min 0, max 39)",
			"Error message",
			Tango::OPERATOR);
	command_list.push_back(pgetErrorCmd);

	/*----- PROTECTED REGION ID(MAGSrvClass::command_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		MAGSrvClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void MAGSrvClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(MAGSrvClass::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		MAGSrvClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void MAGSrvClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		MAGSrv *dev = static_cast<MAGSrv *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(MAGSrvClass::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : MAGSrvClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *MAGSrvClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(MAGSrvClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	MAGSrvClass::Additional Methods
} //	namespace
