/*----- PROTECTED REGION ID(ModbusStateMachine.cpp) ENABLED START -----*/
// kate: replace-tabs off; indent-width 4; indent-mode cstyle; remove-trailing-spaces all; tab-indents on; tab-width 4; indent-width 4
//=============================================================================
//
// file :        ModbusStateMachine.cpp
//
// description : State machine file for the Modbus class
//
// project :     Modbus
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
// $Author: pascal_verdier $
//
// $Revision: 1.2 $
// $Date: 2012-11-07 08:56:13 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Modbus.h>

/*----- PROTECTED REGION END -----*/	//	Modbus::ModbusStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Modbus_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ForceSingleCoil_allowed()
 *	Description : Execution allowed for ForceSingleCoil attribute
 */
//--------------------------------------------------------
bool Modbus::is_ForceSingleCoil_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ForceSingleCoil command.
	/*----- PROTECTED REGION ID(Modbus::ForceSingleCoilStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ForceSingleCoilStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadCoilStatus_allowed()
 *	Description : Execution allowed for ReadCoilStatus attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadCoilStatus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadCoilStatus command.
	/*----- PROTECTED REGION ID(Modbus::ReadCoilStatusStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadCoilStatusStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputStatus_allowed()
 *	Description : Execution allowed for ReadInputStatus attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputStatus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputStatus command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputStatusStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputStatusStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadHoldingRegisters_allowed()
 *	Description : Execution allowed for ReadHoldingRegisters attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadHoldingRegisters_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadHoldingRegisters command.
	/*----- PROTECTED REGION ID(Modbus::ReadHoldingRegistersStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadHoldingRegistersStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputRegisters_allowed()
 *	Description : Execution allowed for ReadInputRegisters attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputRegisters_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputRegisters command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputRegistersStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputRegistersStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_PresetSingleRegister_allowed()
 *	Description : Execution allowed for PresetSingleRegister attribute
 */
//--------------------------------------------------------
bool Modbus::is_PresetSingleRegister_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PresetSingleRegister command.
	/*----- PROTECTED REGION ID(Modbus::PresetSingleRegisterStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::PresetSingleRegisterStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadExceptionStatus_allowed()
 *	Description : Execution allowed for ReadExceptionStatus attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadExceptionStatus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadExceptionStatus command.
	/*----- PROTECTED REGION ID(Modbus::ReadExceptionStatusStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadExceptionStatusStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_FetchCommEventCtr_allowed()
 *	Description : Execution allowed for FetchCommEventCtr attribute
 */
//--------------------------------------------------------
bool Modbus::is_FetchCommEventCtr_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for FetchCommEventCtr command.
	/*----- PROTECTED REGION ID(Modbus::FetchCommEventCtrStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::FetchCommEventCtrStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ForceMultipleCoils_allowed()
 *	Description : Execution allowed for ForceMultipleCoils attribute
 */
//--------------------------------------------------------
bool Modbus::is_ForceMultipleCoils_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ForceMultipleCoils command.
	/*----- PROTECTED REGION ID(Modbus::ForceMultipleCoilsStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ForceMultipleCoilsStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadMultipleCoilsStatus_allowed()
 *	Description : Execution allowed for ReadMultipleCoilsStatus attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadMultipleCoilsStatus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadMultipleCoilsStatus command.
	/*----- PROTECTED REGION ID(Modbus::ReadMultipleCoilsStatusStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadMultipleCoilsStatusStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_PresetMultipleRegisters_allowed()
 *	Description : Execution allowed for PresetMultipleRegisters attribute
 */
//--------------------------------------------------------
bool Modbus::is_PresetMultipleRegisters_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PresetMultipleRegisters command.
	/*----- PROTECTED REGION ID(Modbus::PresetMultipleRegistersStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::PresetMultipleRegistersStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_MaskWriteRegister_allowed()
 *	Description : Execution allowed for MaskWriteRegister attribute
 */
//--------------------------------------------------------
bool Modbus::is_MaskWriteRegister_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MaskWriteRegister command.
	/*----- PROTECTED REGION ID(Modbus::MaskWriteRegisterStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::MaskWriteRegisterStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadWriteRegister_allowed()
 *	Description : Execution allowed for ReadWriteRegister attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadWriteRegister_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadWriteRegister command.
	/*----- PROTECTED REGION ID(Modbus::ReadWriteRegisterStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadWriteRegisterStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_PresetSingleRegisterBroadcast_allowed()
 *	Description : Execution allowed for PresetSingleRegisterBroadcast attribute
 */
//--------------------------------------------------------
bool Modbus::is_PresetSingleRegisterBroadcast_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PresetSingleRegisterBroadcast command.
	/*----- PROTECTED REGION ID(Modbus::PresetSingleRegisterBroadcastStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::PresetSingleRegisterBroadcastStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputRegistersUNS40_allowed()
 *	Description : Execution allowed for ReadInputRegistersUNS40 attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputRegistersUNS40_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputRegistersUNS40 command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputRegistersUNS40StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputRegistersUNS40StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadHoldingRegistersUNS40_allowed()
 *	Description : Execution allowed for ReadHoldingRegistersUNS40 attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadHoldingRegistersUNS40_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadHoldingRegistersUNS40 command.
	/*----- PROTECTED REGION ID(Modbus::ReadHoldingRegistersUNS40StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadHoldingRegistersUNS40StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_PresetSingleRegisterUNS40_allowed()
 *	Description : Execution allowed for PresetSingleRegisterUNS40 attribute
 */
//--------------------------------------------------------
bool Modbus::is_PresetSingleRegisterUNS40_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PresetSingleRegisterUNS40 command.
	/*----- PROTECTED REGION ID(Modbus::PresetSingleRegisterUNS40StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::PresetSingleRegisterUNS40StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputRegistersUNS32_allowed()
 *	Description : Execution allowed for ReadInputRegistersUNS32 attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputRegistersUNS32_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputRegistersUNS32 command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputRegistersUNS32StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputRegistersUNS32StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadHoldingRegistersUNS32_allowed()
 *	Description : Execution allowed for ReadHoldingRegistersUNS32 attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadHoldingRegistersUNS32_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadHoldingRegistersUNS32 command.
	/*----- PROTECTED REGION ID(Modbus::ReadHoldingRegistersUNS32StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadHoldingRegistersUNS32StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_PresetSingleRegisterUNS32_allowed()
 *	Description : Execution allowed for PresetSingleRegisterUNS32 attribute
 */
//--------------------------------------------------------
bool Modbus::is_PresetSingleRegisterUNS32_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PresetSingleRegisterUNS32 command.
	/*----- PROTECTED REGION ID(Modbus::PresetSingleRegisterUNS32StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::PresetSingleRegisterUNS32StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputString_allowed()
 *	Description : Execution allowed for ReadInputString attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputString_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputString command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputStringStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputStringStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadHoldingString_allowed()
 *	Description : Execution allowed for ReadHoldingString attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadHoldingString_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadHoldingString command.
	/*----- PROTECTED REGION ID(Modbus::ReadHoldingStringStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadHoldingStringStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_PresetStringRegister_allowed()
 *	Description : Execution allowed for PresetStringRegister attribute
 */
//--------------------------------------------------------
bool Modbus::is_PresetStringRegister_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PresetStringRegister command.
	/*----- PROTECTED REGION ID(Modbus::PresetStringRegisterStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::PresetStringRegisterStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputRegistersSIG16_allowed()
 *	Description : Execution allowed for ReadInputRegistersSIG16 attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputRegistersSIG16_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputRegistersSIG16 command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputRegistersSIG16StateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputRegistersSIG16StateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ReadInputRegistersFloat_allowed()
 *	Description : Execution allowed for ReadInputRegistersFloat attribute
 */
//--------------------------------------------------------
bool Modbus::is_ReadInputRegistersFloat_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadInputRegistersFloat command.
	/*----- PROTECTED REGION ID(Modbus::ReadInputRegistersFloatStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ReadInputRegistersFloatStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Modbus::is_ForceSingleCoilAmplitude_allowed()
 *	Description : Execution allowed for ForceSingleCoilAmplitude attribute
 */
//--------------------------------------------------------
bool Modbus::is_ForceSingleCoilAmplitude_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ForceSingleCoilAmplitude command.
	/*----- PROTECTED REGION ID(Modbus::ForceSingleCoilAmplitudeStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Modbus::ForceSingleCoilAmplitudeStateAllowed
	return true;
}

}	//	End of namespace
