/*----- PROTECTED REGION ID(VacuumValveSrvClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        VacuumValveSrvClass.cpp
//
// description : C++ source for the VacuumValveSrvClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the VacuumValveSrv once per process.
//
// project :     Valve control server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <VacuumValveSrvClass.h>

/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass.cpp

//-------------------------------------------------------------------
/**
 *	Create VacuumValveSrvClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_VacuumValveSrv_class(const char *name) {
		return VacuumValveSrv_ns::VacuumValveSrvClass::init(name);
	}
}

namespace VacuumValveSrv_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
VacuumValveSrvClass *VacuumValveSrvClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		VacuumValveSrvClass::VacuumValveSrvClass(string &s)
 * description : 	constructor for the VacuumValveSrvClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
VacuumValveSrvClass::VacuumValveSrvClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering VacuumValveSrvClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(VacuumValveSrvClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::constructor

	cout2 << "Leaving VacuumValveSrvClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		VacuumValveSrvClass::~VacuumValveSrvClass()
 * description : 	destructor for the VacuumValveSrvClass
 */
//--------------------------------------------------------
VacuumValveSrvClass::~VacuumValveSrvClass()
{
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		VacuumValveSrvClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
VacuumValveSrvClass *VacuumValveSrvClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new VacuumValveSrvClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		VacuumValveSrvClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
VacuumValveSrvClass *VacuumValveSrvClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		OpenClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OpenClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OpenClass::execute(): arrived" << endl;
	((static_cast<VacuumValveSrv *>(device))->open());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CloseClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CloseClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CloseClass::execute(): arrived" << endl;
	((static_cast<VacuumValveSrv *>(device))->close());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;
	((static_cast<VacuumValveSrv *>(device))->reset());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum VacuumValveSrvClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum VacuumValveSrvClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum VacuumValveSrvClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void VacuumValveSrvClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "AnalogIN";
	prop_desc = "Device file to read for the analog value associated with the valve";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "GPIO_Device";
	prop_desc = "Device server to access GPIO";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "GPIO_Check";
	prop_desc = "GPIO pin to check the correct operation of the control relay";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "GPIO_Close";
	prop_desc = "GPIO pin to check the close status of the valve";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "GPIO_Command";
	prop_desc = "GPIO pin to control the valve opening";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "GPIO_Open";
	prop_desc = "GPIO pin to check the open status of the valve";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ValveDelay";
	prop_desc = "Valve open/close delay in ms";
	prop_def  = "1500";
	vect_data.clear();
	vect_data.push_back("1500");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "HardDisable";
	prop_desc = "Set this property to true to prevent the valve from operating";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void VacuumValveSrvClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Valve control server");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void VacuumValveSrvClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new VacuumValveSrv(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		VacuumValveSrv *dev = static_cast<VacuumValveSrv *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(VacuumValveSrvClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void VacuumValveSrvClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::attribute_factory_before
	//	Attribute : RawVoltage
	RawVoltageAttrib	*rawvoltage = new RawVoltageAttrib();
	Tango::UserDefaultAttrProp	rawvoltage_prop;
	rawvoltage_prop.set_description("Raw analog reading");
	rawvoltage_prop.set_label("Raw voltage");
	rawvoltage_prop.set_unit("V");
	rawvoltage_prop.set_standard_unit("V");
	rawvoltage_prop.set_display_unit("V");
	rawvoltage_prop.set_format("%.3f");
	//	max_value	not set for RawVoltage
	//	min_value	not set for RawVoltage
	//	max_alarm	not set for RawVoltage
	//	min_alarm	not set for RawVoltage
	//	max_warning	not set for RawVoltage
	//	min_warning	not set for RawVoltage
	//	delta_t	not set for RawVoltage
	//	delta_val	not set for RawVoltage
	
	rawvoltage->set_default_properties(rawvoltage_prop);
	//	Not Polled
	rawvoltage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rawvoltage->set_change_event(true, false);
	att_list.push_back(rawvoltage);

	//	Attribute : Pressure
	PressureAttrib	*pressure = new PressureAttrib();
	Tango::UserDefaultAttrProp	pressure_prop;
	pressure_prop.set_description("Pressure");
	pressure_prop.set_label("Pressure");
	pressure_prop.set_unit("mbar");
	pressure_prop.set_standard_unit("mbar");
	pressure_prop.set_display_unit("mbar");
	pressure_prop.set_format("%.3E");
	//	max_value	not set for Pressure
	//	min_value	not set for Pressure
	//	max_alarm	not set for Pressure
	//	min_alarm	not set for Pressure
	//	max_warning	not set for Pressure
	//	min_warning	not set for Pressure
	//	delta_t	not set for Pressure
	//	delta_val	not set for Pressure
	
	pressure->set_default_properties(pressure_prop);
	//	Not Polled
	pressure->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	pressure->set_change_event(true, false);
	att_list.push_back(pressure);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void VacuumValveSrvClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::pipe_factory_before
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void VacuumValveSrvClass::command_factory()
{
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::command_factory_before) ENABLED START -----*/
	
	// Set 500 ms polling perod for command State
	Tango::Command &stateCmd = get_cmd_by_name("State");
	stateCmd.set_polling_period(500);
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::command_factory_before


	//	Command Open
	OpenClass	*pOpenCmd =
		new OpenClass("Open",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOpenCmd);

	//	Command Close
	CloseClass	*pCloseCmd =
		new CloseClass("Close",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCloseCmd);

	//	Command Reset
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);

	/*----- PROTECTED REGION ID(VacuumValveSrvClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		VacuumValveSrvClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void VacuumValveSrvClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(VacuumValveSrvClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		VacuumValveSrvClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void VacuumValveSrvClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		VacuumValveSrv *dev = static_cast<VacuumValveSrv *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(VacuumValveSrvClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : VacuumValveSrvClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *VacuumValveSrvClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(VacuumValveSrvClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	VacuumValveSrvClass::Additional Methods
} //	namespace
