/*----- PROTECTED REGION ID(PolyscienceStateMachine.cpp) ENABLED START -----*/
// kate: replace-tabs off; indent-width 4; indent-mode cstyle; remove-trailing-spaces all; tab-indents on; tab-width 4; indent-width 4
//=============================================================================
//
// file :        PolyscienceStateMachine.cpp
//
// description : State machine file for the Polyscience class
//
// project :     Polyscience series 6000
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Polyscience.h>

/*----- PROTECTED REGION END -----*/	//	Polyscience::PolyscienceStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Polyscience_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Polyscience::is_Temperature_allowed()
 *	Description : Execution allowed for Temperature attribute
 */
//--------------------------------------------------------
bool Polyscience::is_Temperature_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Temperature attribute in read access.
	/*----- PROTECTED REGION ID(Polyscience::TemperatureStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Polyscience::TemperatureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Polyscience::is_Setpoint_allowed()
 *	Description : Execution allowed for Setpoint attribute
 */
//--------------------------------------------------------
bool Polyscience::is_Setpoint_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Setpoint attribute in Write access.
	/*----- PROTECTED REGION ID(Polyscience::SetpointStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Polyscience::SetpointStateAllowed_WRITE

	//	Not any excluded states for Setpoint attribute in read access.
	/*----- PROTECTED REGION ID(Polyscience::SetpointStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Polyscience::SetpointStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Polyscience::is_Flow_allowed()
 *	Description : Execution allowed for Flow attribute
 */
//--------------------------------------------------------
bool Polyscience::is_Flow_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Flow attribute in read access.
	/*----- PROTECTED REGION ID(Polyscience::FlowStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Polyscience::FlowStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Polyscience::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool Polyscience::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(Polyscience::StartStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Polyscience::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Polyscience::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool Polyscience::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(Polyscience::StopStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Polyscience::StopStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(Polyscience::PolyscienceStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Polyscience::PolyscienceStateAllowed.AdditionalMethods

}	//	End of namespace
