/*----- PROTECTED REGION ID(DryVacSrvClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        DryVacSrvClass.cpp
//
// description : C++ source for the DryVacSrvClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the DryVacSrv once per process.
//
// project :     DryVac Device Server
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <DryVacSrvClass.h>

/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass.cpp

//-------------------------------------------------------------------
/**
 *	Create DryVacSrvClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_DryVacSrv_class(const char *name) {
		return DryVacSrv_ns::DryVacSrvClass::init(name);
	}
}

namespace DryVacSrv_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
DryVacSrvClass *DryVacSrvClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		DryVacSrvClass::DryVacSrvClass(string &s)
 * description : 	constructor for the DryVacSrvClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
DryVacSrvClass::DryVacSrvClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering DryVacSrvClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(DryVacSrvClass::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::constructor

	cout2 << "Leaving DryVacSrvClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		DryVacSrvClass::~DryVacSrvClass()
 * description : 	destructor for the DryVacSrvClass
 */
//--------------------------------------------------------
DryVacSrvClass::~DryVacSrvClass()
{
	/*----- PROTECTED REGION ID(DryVacSrvClass::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		DryVacSrvClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
DryVacSrvClass *DryVacSrvClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new DryVacSrvClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		DryVacSrvClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
DryVacSrvClass *DryVacSrvClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StartClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartClass::execute(): arrived" << endl;
	((static_cast<DryVacSrv *>(device))->start());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<DryVacSrv *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;
	((static_cast<DryVacSrv *>(device))->reset());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum DryVacSrvClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum DryVacSrvClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum DryVacSrvClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void DryVacSrvClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "Address";
	prop_desc = "Address of the pump on RS485 bus";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PollingTime";
	prop_desc = "Polling time for attributes from the inverter (in ms)";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Port";
	prop_desc = "Serial port for the MODBUS communication";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PortConfiguration";
	prop_desc = "Serial port configuration. A three character string containing:\n1) Data bits (5, 6, 7 or 8)\n2) Parity (N for none, E for even, O for odd)\n3) Stop bits (1 or 2)\nDefault is `8N1`.";
	prop_def  = "8N1";
	vect_data.clear();
	vect_data.push_back("8N1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PortBaudrate";
	prop_desc = "Port baud rate (default: 9600)";
	prop_def  = "9600";
	vect_data.clear();
	vect_data.push_back("9600");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "CompAirDetect";
	prop_desc = "GPIO bit to check for compressed air presence";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "EnBallast";
	prop_desc = "GPIO pin to enable ballast";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "EnPurge";
	prop_desc = "GPIO pin to enable purge on output bearing";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "WaterCoolingValve";
	prop_desc = "Device server that controls the water cooling valve";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AnalogIN";
	prop_desc = "Analog input attribute for pressure reading";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "WaterCloseTemperature";
	prop_desc = "The pump temperature the device server wait before closing the water valve when the pump stops (in °C)";
	prop_def  = "35";
	vect_data.clear();
	vect_data.push_back("35");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DisableWater";
	prop_desc = "Disable automatic water valve control by the pump device server";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void DryVacSrvClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("DryVac Device Server");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Device server for a Leybold DryVac screw vacuum pump. Depends on libmodbus for serial communication with the pump.");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("DryVacSrv");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void DryVacSrvClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(DryVacSrvClass::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new DryVacSrv(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		DryVacSrv *dev = static_cast<DryVacSrv *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(DryVacSrvClass::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void DryVacSrvClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(DryVacSrvClass::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::attribute_factory_before
	//	Attribute : FreqSetpoint
	FreqSetpointAttrib	*freqsetpoint = new FreqSetpointAttrib();
	Tango::UserDefaultAttrProp	freqsetpoint_prop;
	freqsetpoint_prop.set_description("Frequency setpoint for the inverter");
	freqsetpoint_prop.set_label("Frequency setpoint");
	freqsetpoint_prop.set_unit("Hz");
	freqsetpoint_prop.set_standard_unit("Hz");
	freqsetpoint_prop.set_display_unit("Hz");
	freqsetpoint_prop.set_format("%.2f");
	freqsetpoint_prop.set_max_value("120");
	freqsetpoint_prop.set_min_value("0");
	//	max_alarm	not set for FreqSetpoint
	//	min_alarm	not set for FreqSetpoint
	//	max_warning	not set for FreqSetpoint
	//	min_warning	not set for FreqSetpoint
	//	delta_t	not set for FreqSetpoint
	//	delta_val	not set for FreqSetpoint
	
	freqsetpoint->set_default_properties(freqsetpoint_prop);
	//	Not Polled
	freqsetpoint->set_disp_level(Tango::OPERATOR);
	freqsetpoint->set_memorized();
	freqsetpoint->set_memorized_init(true);
	freqsetpoint->set_change_event(true, false);
	att_list.push_back(freqsetpoint);

	//	Attribute : Frequency
	FrequencyAttrib	*frequency = new FrequencyAttrib();
	Tango::UserDefaultAttrProp	frequency_prop;
	frequency_prop.set_description("Converter output frequency");
	frequency_prop.set_label("Fequency");
	frequency_prop.set_unit("Hz");
	frequency_prop.set_standard_unit("Hz");
	frequency_prop.set_display_unit("Hz");
	frequency_prop.set_format("%.2f");
	//	max_value	not set for Frequency
	//	min_value	not set for Frequency
	//	max_alarm	not set for Frequency
	//	min_alarm	not set for Frequency
	//	max_warning	not set for Frequency
	//	min_warning	not set for Frequency
	//	delta_t	not set for Frequency
	//	delta_val	not set for Frequency
	
	frequency->set_default_properties(frequency_prop);
	//	Not Polled
	frequency->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	frequency->set_change_event(true, false);
	att_list.push_back(frequency);

	//	Attribute : Voltage
	VoltageAttrib	*voltage = new VoltageAttrib();
	Tango::UserDefaultAttrProp	voltage_prop;
	voltage_prop.set_description("Converter output voltage");
	voltage_prop.set_label("Voltage");
	voltage_prop.set_unit("V");
	voltage_prop.set_standard_unit("V");
	voltage_prop.set_display_unit("V");
	voltage_prop.set_format("%.1f");
	//	max_value	not set for Voltage
	//	min_value	not set for Voltage
	//	max_alarm	not set for Voltage
	//	min_alarm	not set for Voltage
	//	max_warning	not set for Voltage
	//	min_warning	not set for Voltage
	//	delta_t	not set for Voltage
	//	delta_val	not set for Voltage
	
	voltage->set_default_properties(voltage_prop);
	//	Not Polled
	voltage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	voltage->set_change_event(true, false);
	att_list.push_back(voltage);

	//	Attribute : Current
	CurrentAttrib	*current = new CurrentAttrib();
	Tango::UserDefaultAttrProp	current_prop;
	current_prop.set_description("Converter output current");
	current_prop.set_label("Current");
	current_prop.set_unit("A");
	current_prop.set_standard_unit("A");
	current_prop.set_display_unit("A");
	current_prop.set_format("%.1f");
	//	max_value	not set for Current
	//	min_value	not set for Current
	//	max_alarm	not set for Current
	//	min_alarm	not set for Current
	//	max_warning	not set for Current
	//	min_warning	not set for Current
	//	delta_t	not set for Current
	//	delta_val	not set for Current
	
	current->set_default_properties(current_prop);
	//	Not Polled
	current->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	current->set_change_event(true, false);
	att_list.push_back(current);

	//	Attribute : Power
	PowerAttrib	*power = new PowerAttrib();
	Tango::UserDefaultAttrProp	power_prop;
	power_prop.set_description("Converter output power");
	power_prop.set_label("Power");
	power_prop.set_unit("kW");
	power_prop.set_standard_unit("kW");
	power_prop.set_display_unit("kW");
	power_prop.set_format("%.1f");
	//	max_value	not set for Power
	//	min_value	not set for Power
	//	max_alarm	not set for Power
	//	min_alarm	not set for Power
	//	max_warning	not set for Power
	//	min_warning	not set for Power
	//	delta_t	not set for Power
	//	delta_val	not set for Power
	
	power->set_default_properties(power_prop);
	//	Not Polled
	power->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	power->set_change_event(true, false);
	att_list.push_back(power);

	//	Attribute : Temperature
	TemperatureAttrib	*temperature = new TemperatureAttrib();
	Tango::UserDefaultAttrProp	temperature_prop;
	temperature_prop.set_description("Converter heatsink temperature");
	temperature_prop.set_label("Temperature");
	temperature_prop.set_unit("°C");
	temperature_prop.set_standard_unit("°C");
	temperature_prop.set_display_unit("°C");
	//	format	not set for Temperature
	//	max_value	not set for Temperature
	//	min_value	not set for Temperature
	//	max_alarm	not set for Temperature
	//	min_alarm	not set for Temperature
	//	max_warning	not set for Temperature
	//	min_warning	not set for Temperature
	//	delta_t	not set for Temperature
	//	delta_val	not set for Temperature
	
	temperature->set_default_properties(temperature_prop);
	//	Not Polled
	temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	temperature->set_change_event(true, false);
	att_list.push_back(temperature);

	//	Attribute : Pressure
	PressureAttrib	*pressure = new PressureAttrib();
	Tango::UserDefaultAttrProp	pressure_prop;
	pressure_prop.set_description("Pressure al the pump inlet");
	pressure_prop.set_label("Pressure");
	pressure_prop.set_unit("mbar");
	pressure_prop.set_standard_unit("mbar");
	pressure_prop.set_display_unit("mbar");
	pressure_prop.set_format("%.3E");
	//	max_value	not set for Pressure
	//	min_value	not set for Pressure
	//	max_alarm	not set for Pressure
	//	min_alarm	not set for Pressure
	//	max_warning	not set for Pressure
	//	min_warning	not set for Pressure
	//	delta_t	not set for Pressure
	//	delta_val	not set for Pressure
	
	pressure->set_default_properties(pressure_prop);
	//	Not Polled
	pressure->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	pressure->set_change_event(true, false);
	att_list.push_back(pressure);

	//	Attribute : EnablePurge
	EnablePurgeAttrib	*enablepurge = new EnablePurgeAttrib();
	Tango::UserDefaultAttrProp	enablepurge_prop;
	//	description	not set for EnablePurge
	//	label	not set for EnablePurge
	//	unit	not set for EnablePurge
	//	standard_unit	not set for EnablePurge
	//	display_unit	not set for EnablePurge
	//	format	not set for EnablePurge
	//	max_value	not set for EnablePurge
	//	min_value	not set for EnablePurge
	//	max_alarm	not set for EnablePurge
	//	min_alarm	not set for EnablePurge
	//	max_warning	not set for EnablePurge
	//	min_warning	not set for EnablePurge
	//	delta_t	not set for EnablePurge
	//	delta_val	not set for EnablePurge
	
	enablepurge->set_default_properties(enablepurge_prop);
	//	Not Polled
	enablepurge->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	enablepurge->set_change_event(true, false);
	att_list.push_back(enablepurge);

	//	Attribute : EnableBallast
	EnableBallastAttrib	*enableballast = new EnableBallastAttrib();
	Tango::UserDefaultAttrProp	enableballast_prop;
	//	description	not set for EnableBallast
	//	label	not set for EnableBallast
	//	unit	not set for EnableBallast
	//	standard_unit	not set for EnableBallast
	//	display_unit	not set for EnableBallast
	//	format	not set for EnableBallast
	//	max_value	not set for EnableBallast
	//	min_value	not set for EnableBallast
	//	max_alarm	not set for EnableBallast
	//	min_alarm	not set for EnableBallast
	//	max_warning	not set for EnableBallast
	//	min_warning	not set for EnableBallast
	//	delta_t	not set for EnableBallast
	//	delta_val	not set for EnableBallast
	
	enableballast->set_default_properties(enableballast_prop);
	//	Not Polled
	enableballast->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	enableballast->set_change_event(true, false);
	att_list.push_back(enableballast);

	//	Attribute : CompressedAir
	CompressedAirAttrib	*compressedair = new CompressedAirAttrib();
	Tango::UserDefaultAttrProp	compressedair_prop;
	//	description	not set for CompressedAir
	//	label	not set for CompressedAir
	//	unit	not set for CompressedAir
	//	standard_unit	not set for CompressedAir
	//	display_unit	not set for CompressedAir
	//	format	not set for CompressedAir
	//	max_value	not set for CompressedAir
	//	min_value	not set for CompressedAir
	//	max_alarm	not set for CompressedAir
	//	min_alarm	not set for CompressedAir
	//	max_warning	not set for CompressedAir
	//	min_warning	not set for CompressedAir
	//	delta_t	not set for CompressedAir
	//	delta_val	not set for CompressedAir
	
	compressedair->set_default_properties(compressedair_prop);
	//	Not Polled
	compressedair->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	compressedair->set_change_event(true, false);
	att_list.push_back(compressedair);

	//	Attribute : WaterValve
	WaterValveAttrib	*watervalve = new WaterValveAttrib();
	Tango::UserDefaultAttrProp	watervalve_prop;
	watervalve_prop.set_description("Water valve status");
	watervalve_prop.set_label("Water valve");
	//	unit	not set for WaterValve
	//	standard_unit	not set for WaterValve
	//	display_unit	not set for WaterValve
	//	format	not set for WaterValve
	//	max_value	not set for WaterValve
	//	min_value	not set for WaterValve
	//	max_alarm	not set for WaterValve
	//	min_alarm	not set for WaterValve
	//	max_warning	not set for WaterValve
	//	min_warning	not set for WaterValve
	//	delta_t	not set for WaterValve
	//	delta_val	not set for WaterValve
	
	watervalve->set_default_properties(watervalve_prop);
	//	Not Polled
	watervalve->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	watervalve->set_change_event(true, false);
	att_list.push_back(watervalve);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(DryVacSrvClass::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void DryVacSrvClass::command_factory()
{
	/*----- PROTECTED REGION ID(DryVacSrvClass::command_factory_before) ENABLED START -----*/

	// Set 500 ms polling perod for command State
	Tango::Command &stateCmd = get_cmd_by_name("State");
	stateCmd.set_polling_period(500);

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::command_factory_before


	//	Command Start
	StartClass	*pStartCmd =
		new StartClass("Start",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCmd);

	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	//	Command Reset
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);

	/*----- PROTECTED REGION ID(DryVacSrvClass::command_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		DryVacSrvClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void DryVacSrvClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(DryVacSrvClass::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		DryVacSrvClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void DryVacSrvClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		DryVacSrv *dev = static_cast<DryVacSrv *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(DryVacSrvClass::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : DryVacSrvClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *DryVacSrvClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(DryVacSrvClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	DryVacSrvClass::Additional Methods
} //	namespace
